-- requirements
require("config.lazy_setup")
require("config.colorschemes_setup")
require("config.nvim_tree_setup")
require("config.lualine_setup")
require("config.illuminate_setup")
require("config.grapple_setup")
require("config.transparent_setup")
require("config.notify_setup")
require("config.dashboard_setup")
require("config.options_keymaps")
